language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

git:
  submodules: false

env:
 - TEST=tests/language/cast.swift

before_install: 
 - ant redist
  
script: 
 - ./dist/swift-svn/bin/swift $TEST 

